export const RESET_STORE = 'RESET_STORE';
export const GET_ERRORS ="GET_ERRORS";
export const GET_QYTETETS ="GET_QYTETETS";
export const GET_QYTETI="GET_QYTETI";
export const CREATE_QYTETI="CREATE_QYTETI";
export const DELETE_QYTETI="DELETE_QYTETI";
export const GET_QYTETI_COUNT = "GET_QYTETI_COUNT";

export const GET_SPITALIS ="GET_SPITALIS";
export const GET_SPITALI="GET_SPITALI";
export const CREATE_SPITALI="CREATE_SPITALI";
export const DELETE_SPITALI="DELETE_SPITALI";
export const GET_SPITALI_COUNT = 'GET_SPITALI_COUNT';

export const GET_REPARTS ="GET_REPARTS";
export const GET_REPARTI="GET_REPARTI";
export const CREATE_REPARTI="CREATE_REPARTI";
export const DELETE_REPARTI="DELETE_REPARTI";

export const GET_MJEKETS ="GET_MJEKETS";
export const GET_MJEKET="GET_MJEKETS";
export const CREATE_MJEKET="CREATE_MJEKETS";
export const DELETE_MJEKET="DELETE_MJEKETS";


export const GET_PACINETS ="GET_PACINETS";
export const GET_PACINETI="GET_PACINETI";
export const CREATE_PACINETI="CREATE_PACINETI";
export const DELETE_PACIENTI="DELETE_PACIENTI";
export const GET_PACIENTI_COUNT = "GET_PACIENTI_COUNT";



