# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: medical_record.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'medical_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14medical_record.proto\x12\x0fmedical.records\"F\n\tLabResult\x12\x10\n\x08testType\x18\x01 \x01(\t\x12\x13\n\x0bresultValue\x18\x02 \x01(\t\x12\x12\n\nresultDate\x18\x03 \x01(\t\"A\n\x05Image\x12\x0f\n\x07\x66ileUrl\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nuploadedAt\x18\x03 \x01(\t\"\xe0\x01\n\rMedicalRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tpacientId\x18\x02 \x01(\t\x12\x11\n\tdiagnosis\x18\x03 \x01(\t\x12\x15\n\rtreatmentPlan\x18\x04 \x01(\t\x12\r\n\x05notes\x18\x05 \x01(\t\x12\x11\n\tcreatedAt\x18\x06 \x01(\t\x12.\n\nlabResults\x18\x07 \x03(\x0b\x32\x1a.medical.records.LabResult\x12\x34\n\rmedicalImages\x18\x08 \x03(\x0b\x32\x1d.medical.records.MedicalImage\"F\n\x0cMedicalImage\x12\x11\n\timageType\x18\x01 \x01(\t\x12\x0f\n\x07\x66ileUrl\x18\x02 \x01(\t\x12\x12\n\nuploadedAt\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medical_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LABRESULT']._serialized_start=41
  _globals['_LABRESULT']._serialized_end=111
  _globals['_IMAGE']._serialized_start=113
  _globals['_IMAGE']._serialized_end=178
  _globals['_MEDICALRECORD']._serialized_start=181
  _globals['_MEDICALRECORD']._serialized_end=405
  _globals['_MEDICALIMAGE']._serialized_start=407
  _globals['_MEDICALIMAGE']._serialized_end=477
# @@protoc_insertion_point(module_scope)
