version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  kafka:
   image: bitnami/kafka:latest
   restart: always
   ports:
     - "9092:9092"   # Internal Kafka broker
     - "9094:9094"   # External listener (p.sh për localhost jashtë Docker)
   environment:
     KAFKA_KRAFT_CLUSTER_ID: qwertyuiopasdfghjklzxcvbnm123456 # 32-char ID, random or generated
     KAFKA_CFG_NODE_ID: 0
     KAFKA_CFG_PROCESS_ROLES: controller,broker
     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
     ALLOW_PLAINTEXT_LISTENER: "yes"
   volumes:
     - kafka_data:/bitnami/kafka
   depends_on:
     - mongo

volumes:
  mongodb_data:
  kafka_data:
