server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: api_gateway
  lifecycle:
    timeout-per-shutdown-phase: 15s

  redis:
    host: localhost
    port: 6379
    timeout: 1s

  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000 # 2 seconds in milliseconds
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s

      default-filters:
        - SaveSession
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false

      routes:
        - id: menaxhimispitalit-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/menaxhimispitalit/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: menaxhimispitalitCircuitBreaker
                fallbackUri: forward:/menaxhimispitalit-fallback

        - id: medical-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/medical/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: medicalCircuitBreaker
                fallbackUri: forward:/medical-fallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

    spring:
     security:
      oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/menaxhimiIspitalit
          jwk-set-uri: http://localhost:8080/realms/menaxhimiIspitalit/protocol/openid-connect/certs
